version: 2.0
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout:
      # Login to docker
      - run:
          name: Install requirements
          command:
            pip install -r requirements.txt
      - run:
          name: Python test
          command:
            python tests.py
      - store_test_results:
          path: build/test-results
