version: 2.0
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout:
      - run:
          name: Python test
          command:
            python tests.py
      - store_test_results:
          path: build/test-results
